[package]
name = "test-simple"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
crate_interface.workspace = true
define-simple-traits.workspace = true
impl-simple-traits.workspace = true
