[package]
name = "impl-simple-traits"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
crate_interface.workspace = true
define-simple-traits.workspace = true
