[package]
name = "test-weak-partial"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
crate_interface.workspace = true
define-weak-traits.workspace = true
impl-weak-partial.workspace = true
